### ISSUE TITLE
VOWEL VOCALIC R instead of DEPENDENT VOCALIC R in Ksharanam and ITRANS

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-engine#1]
**Describe the bug**
When using the `Ksharanam` and `ITRANS` schemes, the vowel `ऋ` is output instead of the vowel sign ` ृ`, when typed after a consonant. Reproducible in `Devanagari`, `Grantha` and possibly other scripts. Not reproducible in `Baraha`, `Barahavat` and `Harvard-Kyoto` schemes.

**To Reproduce**
1. Choose `ITRANS` scheme.
2. Choose `Devanagari` output.
3. Type `kRRi`.

**Expected behavior**
`कृ` is output.

**Actual behaviour**
`क्ऋ` is output.

**Desktop (please complete the following information):**
 - Version 2.0-alpha.1

**Comment by ratreya** [comment]
Resolved by e184f641ad54a3689eecdb66a5b08e715dfa1dc8
This was actually a major bug that required a complete redesign of the Engine algorithm. Thanks for catching and reporting!
